### ISSUE TITLE
missing build includes

### ISSUE THREAD

**Issue by YeltsinMartin** [martsalz/VxWorks_Raspberry_Pi#1]
while running : CROSS_COMPILE=aarch64-linux-gnu- make

unable to find necessary includes during compilation. Did you have this issue when you compiled uboot ?

include/image.h:1395:12: fatal error: openssl/evp.h: No such file or directory
 1395 | #  include <openssl/evp.h>

**Comment by YeltsinMartin** [comment]
compiles with  v2021.01 tag of uboot.
